name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # or master, or any branch you want
  workflow_dispatch: # allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Set up Docker Buildx (advanced builder)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build and push
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/docker-node-app:latest
