name: Release and Docker Publish

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Node.js + pnpm for semantic-release
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install -g pnpm
      - run: pnpm install

      # Run semantic-release (bumps version + creates Git tag)
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: npx semantic-release 
  docker:
    needs: release
    runs-on: ubuntu-latest
    if: github.ref_type == 'tag'   # only run if a release created a tag
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version parts
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "MAJOR=${VERSION%%.*}" >> $GITHUB_ENV
          echo "MINOR=${VERSION%.*}" >> $GITHUB_ENV

      - name: Build & push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/docker-node-app:${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/docker-node-app:${{ env.MINOR }}
            ${{ secrets.DOCKER_USERNAME }}/docker-node-app:${{ env.MAJOR }}
            ${{ secrets.DOCKER_USERNAME }}/docker-node-app:latest
