name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # Use a PAT to trigger other workflows
          token: ${{ secrets.PAT_TOKEN }}

      # Node.js + pnpm for semantic-release
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm install -g pnpm
      - run: pnpm install

      # Run semantic-release (bumps version + creates Git tag)
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          HUSKY: 0
        run: npx semantic-release